# Prometheus creates the database that will house all data. It is currently designed with a MySQL database engine.
from conf import *
from sqlalchemy import MetaData, Column, Integer, String, Float, create_engine, __version__
from sqlalchemy.ext.declarative import declarative_base

# Check which version of SQLAlchemy is currently being used.
print "Current SQLAlchemy Version: " + __version__
Base = declarative_base()
metadata = MetaData()


class Olympus(Base):
    __tablename__ = 'olympus'
    id = Column(Integer, primary_key=True)
    project = Column(String(30), nullable=False)
    uid = Column(String(50), nullable=False)
    provider = Column(String(30), nullable=False)
    region = Column(String(30), nullable=False)
    startdate = Column(String(30), nullable=False)
    iteration = Column(Integer, nullable=False)
    iteration_start_time = Column(String(50), nullable=False)
    vm = Column(String(30), nullable=False)
    vmcount = Column(Integer, nullable=False)
    vcpu = Column(Integer, nullable=False)
    ram = Column(Float(30), nullable=False)
    local = Column(Integer, nullable=False)
    block = Column(Integer, nullable=False)
    processor = Column(String(100), nullable=True)
    runtime = Column(Float(30), nullable=True)
    intmulti = Column(Integer, nullable=True)
    floatmulti = Column(Integer, nullable=True)
    memmulti = Column(Integer, nullable=True)
    intsingle = Column(Integer, nullable=True)
    floatsingle = Column(Integer, nullable=True)
    memsingle = Column(Integer, nullable=True)
    totalmulti = Column(Integer, nullable=True)
    totalsingle = Column(Integer, nullable=True)
    aes = Column(Float(30), nullable=True)
    twofish = Column(Float(30), nullable=True)
    sha1 = Column(Float(30), nullable=True)
    sha2 = Column(Float(30), nullable=True)
    bzipcompression = Column(Float(30), nullable=True)
    bzipdecompression = Column(Float(30), nullable=True)
    jpegcompression = Column(Float(30), nullable=True)
    jpegdecompression = Column(Float(30), nullable=True)
    pngcompression = Column(Float(30), nullable=True)
    pngdecompression = Column(Float(30), nullable=True)
    sobel = Column(Float(30), nullable=True)
    lua = Column(Float(30), nullable=True)
    dijkstra = Column(Float(30), nullable=True)
    blackscholes = Column(String(50), nullable=True)
    mandelbrot = Column(Float(30), nullable=True)
    sharpenimage = Column(Float(30), nullable=True)
    blurimage = Column(Float(30), nullable=True)
    sgemm = Column(Float(30), nullable=True)
    dgemm = Column(Float(30), nullable=True)
    sfft = Column(Float(30), nullable=True)
    dfft = Column(Float(30), nullable=True)
    nbody = Column(Float(30), nullable=True)
    raytrace = Column(Float(30), nullable=True)
    copy = Column(Float(30), nullable=True)
    scale = Column(Float(30), nullable=True)
    add = Column(Float(30), nullable=True)
    triad = Column(Float(30), nullable=True)
    runtime_read_seq = Column(Float(30), nullable=True)
    runtime_write_seq = Column(Float(30), nullable=True)
    io_read_seq = Column(Float(30), nullable=True)
    io_write_seq = Column(Float(30), nullable=True)
    iops_read_seq = Column(Float(30), nullable=True)
    iops_write_seq = Column(Float(30), nullable=True)
    bw_read_seq = Column(Float(30), nullable=True)
    bw_write_seq = Column(Float(30), nullable=True)
    runtime_read_seq_async = Column(Float(30), nullable=True)
    runtime_write_seq_async = Column(Float(30), nullable=True)
    io_read_seq_async = Column(Float(30), nullable=True)
    io_write_seq_async = Column(Float(30), nullable=True)
    iops_read_seq_async = Column(Float(30), nullable=True)
    iops_write_seq_async = Column(Float(30), nullable=True)
    bw_read_seq_async = Column(Float(30), nullable=True)
    bw_write_seq_async = Column(Float(30), nullable=True)
    runtime_read_rand = Column(Float(30), nullable=True)
    runtime_write_rand = Column(Float(30), nullable=True)
    io_read_rand = Column(Float(30), nullable=True)
    io_write_rand = Column(Float(30), nullable=True)
    iops_read_rand = Column(Float(30), nullable=True)
    iops_write_rand = Column(Float(30), nullable=True)
    bw_read_rand = Column(Float(30), nullable=True)
    bw_write_rand = Column(Float(30), nullable=True)
    runtime_read_rand_async = Column(Float(30), nullable=True)
    runtime_write_rand_async = Column(Float(30), nullable=True)
    io_read_rand_async = Column(Float(30), nullable=True)
    io_write_rand_async = Column(Float(30), nullable=True)
    iops_read_rand_async = Column(Float(30), nullable=True)
    iops_write_rand_async = Column(Float(30), nullable=True)
    bw_read_rand_async = Column(Float(30), nullable=True)
    bw_write_rand_async = Column(Float(30), nullable=True)
    sender_transfer_mb = Column(Float(30), nullable=True)
    sender_bandwidth_mbps = Column(Float(30), nullable=True)
    receiver_transfer_mb = Column(Float(30), nullable=True)
    receiver_bandwidth_mbps = Column(Float(30), nullable=True)
    iozone_seq_writers = Column(Float(30), nullable=True)
    iozone_seq_rewriters = Column(Float(30), nullable=True)
    iozone_seq_readers = Column(Float(30), nullable=True)
    iozone_seq_rereaders = Column(Float(30), nullable=True)
    iozone_random_readers = Column(Float(30), nullable=True)
    iozone_random_writers = Column(Float(30), nullable=True)
    sysbench_seq_write = Column(Float(30), nullable=True)
    sysbench_seq_read = Column(Float(30), nullable=True)
    sysbench_rand_write = Column(Float(30), nullable=True)
    sysbench_rand_read = Column(Float(30), nullable=True)
    pm_cpu_integer_math = Column(Float(30), nullable=True)
    pm_cpu_floating_math = Column(Float(30), nullable=True)
    pm_cpu_prime_numbers = Column(Float(30), nullable=True)
    pm_cpu_extended_instr = Column(Float(30), nullable=True)
    pm_cpu_compression = Column(Float(30), nullable=True)
    pm_cpu_encryption = Column(Float(30), nullable=True)
    pm_cpu_physics = Column(Float(30), nullable=True)
    pm_cpu_sorting = Column(Float(30), nullable=True)
    pm_cpu_single_threaded = Column(Float(30), nullable=True)
    pm_g2d_simple_vectors = Column(Float(30), nullable=True)
    pm_g2d_complex_vectors = Column(Float(30), nullable=True)
    pm_g2d_fonts_text = Column(Float(30), nullable=True)
    pm_g2d_windows_interface = Column(Float(30), nullable=True)
    pm_g2d_image_filters = Column(Float(30), nullable=True)
    pm_g2d_image_rendering = Column(Float(30), nullable=True)
    pm_g3d_direct_2d = Column(Float(30), nullable=True)
    pm_g3d_direct_x9_simple = Column(Float(30), nullable=True)
    pm_g3d_direct_x9_complex = Column(Float(30), nullable=True)
    pm_g3d_direct_x10 = Column(Float(30), nullable=True)
    pm_g3d_direct_x11 = Column(Float(30), nullable=True)
    pm_g3d_direct_compute = Column(Float(30), nullable=True)
    pm_mem_db_operations = Column(Float(30), nullable=True)
    pm_mem_read_cached = Column(Float(30), nullable=True)
    pm_mem_read_uncached = Column(Float(30), nullable=True)
    pm_mem_write = Column(Float(30), nullable=True)
    pm_mem_available_ram = Column(Float(30), nullable=True)
    pm_mem_latency = Column(Float(30), nullable=True)
    pm_mem_threaded = Column(Float(30), nullable=True)
    pm_disk_seq_read = Column(Float(30), nullable=True)
    pm_disk_seq_write = Column(Float(30), nullable=True)
    pm_disk_ran_seq_rw = Column(Float(30), nullable=True)
    pm_cd_dvd_read = Column(Float(30), nullable=True)
    pm_cpu_mark = Column(Float(30), nullable=True)
    pm_two_d_graphics_mark = Column(Float(30), nullable=True)
    pm_mem_mark = Column(Float(30), nullable=True)
    pm_disk_mark = Column(Float(30), nullable=True)
    pm_three_d_graphics_mark = Column(Float(30), nullable=True)
    pm_passmark_rating = Column(Float(30), nullable=True)
    perlbench_base_copies = Column(String(20), nullable=False)
    perlbench_base_runtime = Column(String(20), nullable=False)
    perlbench_base_rate = Column(String(20), nullable=False)
    perlbench_peak_copies = Column(String(20), nullable=False)
    perlbench_peak_runtime = Column(String(20), nullable=False)
    perlbench_peak_rate = Column(String(20), nullable=False)
    bzip2_base_copies = Column(String(20), nullable=False)
    bzip2_base_runtime = Column(String(20), nullable=False)
    bzip2_base_rate = Column(String(20), nullable=False)
    bzip2_peak_copies = Column(String(20), nullable=False)
    bzip2_peak_runtime = Column(String(20), nullable=False)
    bzip2_peak_rate = Column(String(20), nullable=False)
    gcc_base_copies = Column(String(20), nullable=False)
    gcc_base_runtime = Column(String(20), nullable=False)
    gcc_base_rate = Column(String(20), nullable=False)
    gcc_peak_copies = Column(String(20), nullable=False)
    gcc_peak_runtime = Column(String(20), nullable=False)
    gcc_peak_rate = Column(String(20), nullable=False)
    mcf_base_copies = Column(String(20), nullable=False)
    mcf_base_runtime = Column(String(20), nullable=False)
    mcf_base_rate = Column(String(20), nullable=False)
    mcf_peak_copies = Column(String(20), nullable=False)
    mcf_peak_runtime = Column(String(20), nullable=False)
    mcf_peak_rate = Column(String(20), nullable=False)
    xalancbmk_base_copies = Column(String(20), nullable=False)
    xalancbmk_base_runtime = Column(String(20), nullable=False)
    xalancbmk_base_rate = Column(String(20), nullable=False)
    xalancbmk_peak_copies = Column(String(20), nullable=False)
    xalancbmk_peak_runtime = Column(String(20), nullable=False)
    xalancbmk_peak_rate = Column(String(20), nullable=False)
    soplex_base_copies = Column(String(20), nullable=False)
    soplex_base_runtime = Column(String(20), nullable=False)
    soplex_base_rate = Column(String(20), nullable=False)
    soplex_peak_copies = Column(String(20), nullable=False)
    soplex_peak_runtime = Column(String(20), nullable=False)
    soplex_peak_rate = Column(String(20), nullable=False)
    sphinx3_base_copies = Column(String(20), nullable=False)
    sphinx3_base_runtime = Column(String(20), nullable=False)
    sphinx3_base_rate = Column(String(20), nullable=False)
    sphinx3_peak_copies = Column(String(20), nullable=False)
    sphinx3_peak_runtime = Column(String(20), nullable=False)
    sphinx3_peak_rate = Column(String(20), nullable=False)


# Create an object, db, to act as the connect to the database.
# The SQLEngine object is used to open the connection, which is what is being used in the db variable.
# Format for create_engine is "mysql+pymysql://user:password@host:port/database"
Ignition = create_engine("mysql+pymysql://%s:%s@%s:3306/%s" % (db_user, db_password, db_host, db_name), pool_recycle=30)

# Holds all the database metadata.
Base.metadata.create_all(Ignition)
